### ISSUE TITLE
Create and modify Traffic Classification Policies

### ISSUE THREAD

**Issue by DoktorByte** [ansible-collections/netapp.storagegrid#1]
##### SUMMARY
We want to use the collection "netapp.storagegrid" to create and modify Traffic Classification Policies

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
netapp.storagegrid

##### ADDITIONAL INFORMATION
Traffic Classification Policies were added in StorageGRID version 11.4

**Comment by DoktorByte** [comment]
Hello all,
what is the current status here?
I would still like to create the traffic classification policies via Ansible

Thank you and best regards

**Comment by joshedmonds** [comment]
Yes, sorry for the long delay. Your timing for this follow up is great though - the traffic classification module has been created, it just needs to go through an internal review before being published. It will be part of the 21.10.0 release, expected very shortly.

**Comment by joshedmonds** [comment]
Addressed in commit bb8048cdfa0f7051f086ed795a1a0aa7d1200452.
Available in Ansible Galaxy release 21.10.0.
