### ISSUE TITLE
Storage grid tenant description

### ISSUE THREAD

**Issue by hmarko** [ansible-collections/netapp.storagegrid#18]
Hi.

Will it be possible to include description field in the [netapp.storagegrid.na](http://netapp.storagegrid.na/)_sg_grid_account module

It is part of the /grid/accounts API but cannot find it in ansile module

Thanks !

**Comment by MaxVoitUP** [comment]
We also miss the functionality to write to this field.

In our current workflow, we use the field. The ability to write/read it from ansible would allow us to ansibilify more of our processes. Therefore, we'd greatly appreciate the ability to do so.

**Comment by hmarko75** [comment]
Hi. Until this will be available we overcome this limitation by using direct rest using Ansible 

https://github.com/hmarko75/ansibleforms_service_catalog/blob/master/data/playbooks/sg_create_tenant.yaml

**Comment by joshedmonds** [comment]
`description` parameter has been added to the na_sg_grid_account module in the latest release: https://github.com/ansible-collections/netapp.storagegrid/releases/tag/21.12.0
