### ISSUE TITLE
Unmaintained collection: Removal from Ansible Certified Content program

### ISSUE THREAD

**Issue by alisonlhart** [ansible-collections/netapp.storagegrid#25]
Hello,

Since this collection has had no releases to Ansible Automation Hub in the past 2 years, the Ansible Partner Engineering team has elected to remove this content from the Ansible Certified Content program. 

This is both due to the lack of timely release (none in over a year) , and because the collection has not been tested and released on newer versions of ansible-core (2.14 and 2.15).

The finalized date for this is Feb 29, 2024. If there is a release before then that passes certification standards, the collection will remain part of the certified content program. Otherwise, it will be removed on this date and no longer available to customers through Ansible Automation Hub. 

You can always recertify the collection again if it meets the requirements. Reach out to ansiblepartners@redhat.com for more details and for future certification questions.

**Comment by alisonlhart** [comment]
@joshedmonds That's great news! We'll keep an eye out for it. 

A few other tests for certification have been implemented since the last upload:
- the `meta/runtime.yml` file must specify ">=2.14.0" or above as a minimum version, as all lower are unsupported
- passing tests with `ansible-lint`, docs located here: https://ansible.readthedocs.io/projects/lint/

Please make sure these updates are included as well for certification acceptance.

**Comment by joshedmonds** [comment]
@alisonlhart New version uploaded. 
Tests with 2.14 and 2.15 are passing. `runtime.yml` specifies >=2.14

**Comment by alisonlhart** [comment]
@joshedmonds For certification, the collection will also need to be uploaded to Ansible Automation Hub, under the `netapp` namespace here: https://console.redhat.com/ansible/automation-hub/namespaces/netapp/. Automation Hub is the downstream/product version of community Galaxy, and it has additional tests in place for certification. 

If you do not have access to Automation Hub and need to request a new subscription, [these instructions](https://redhat-connect.gitbook.io/red-hat-partner-connect-general-guide/benefits/software-access) detail how to do so. If you request a new subscription, we may need to move this to email (our team alias is ansiblepartners@redhat.com) so we can get your account number and add it to the namespace for upload permissions.

**Comment by joshedmonds** [comment]
@alisonlhart I believe this is now done but currently awaiting approval.

**Comment by alisonlhart** [comment]
@joshedmonds The collection has been approved on Automation Hub and readded back into the [Red Hat Catalog](https://catalog.redhat.com/software/collection/netapp/storagegrid). Thanks for the quick turnaround on this issue!
