### ISSUE TITLE
Example of na_sg_grid_account.py is confusing

### ISSUE THREAD

**Issue by GuentherDE** [ansible-collections/netapp.storagegrid#4]
##### SUMMARY

In File "na_sg_grid_account.py" the example "name:" and "state:" mismatches. Example will delete tenant. 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://github.com/ansible-collections/netapp.storagegrid/blob/main/plugins/modules/na_sg_grid_account.py

##### ANSIBLE VERSION
AWX 19.2.1

**Comment by joshedmonds** [comment]
Thank you for raising this. It is a documentation bug which we will correct ASAP.

**Comment by joshedmonds** [comment]
Fixed in https://github.com/ansible-collections/netapp.storagegrid/commit/1989da3ca7ab40d0522208c69d0f3139e377714a and will be rolled into a subsequent collection release.
